repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-json
  - id: check-yaml
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: flake8
    args: ['--ignore=F401,F841,W503,E402']
