repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-json
  - id: check-yaml
  - id: fix-encoding-pragma
  - id: trailing-whitespace
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.1
  hooks:
  - id: flake8
    exclude: '^.*(\.testdata\/).*$'
    args: ['--ignore=F401,F841,W503,E402']
# do not apply the pre-commit hooks to all files that are found under folders
# or located at paths containing .testdata
exclude: '^.*(\.testdata\/).*$'
