name: documentation

# always run on push but only run on pull-requests if the "docs" folder
# is affected
on:
  push:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Documentation Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
      - name: Build documentation
        run: |
          SPHINXOPTS='-nW --keep-going' make -C docs html
