name: prepare-release

# run some specific jobs exclusively related to preparing a new
# release inside a release/v** branch

on:
  push:
    branches:
      - 'release/v**'

jobs:
  verify-pkg-versions:
    #if: github.repository == 'aiida-cusp/aiida-cusp'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install `packaging` Dependency
        run: |
          python -m pip install --upgrade pip
          pip install packaging
      - name: Verify internal Package Versions
        run: |
          python .github/helpers/validate_pkg_versions.py
